# Generated by Django 4.1.13 on 2024-03-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questionId', models.CharField(max_length=5)),
                ('studentId', models.CharField(max_length=15)),
                ('conceptId', models.CharField(max_length=20)),
                ('currect_ans', models.TextField()),
                ('score', models.IntegerField()),
                ('entered_ans', models.TextField(null=True)),
                ('skipped_ans', models.TextField(null=True)),
                ('dateAndTime', models.DateTimeField(auto_now_add=True)),
                ('session', models.IntegerField()),
            ],
        ),
    ]
